import { useEffect, useState } from 'react';
import { AlertTriangle, Bot, CheckCircle2, FileVideo, Save, ShieldCheck } from 'lucide-react';
import { caseStudyApi, type CaseStudy } from '../api/caseStudyApi';
import { getErrorMessage } from '../utils/errorMessage';

const CaseStudyPanel = ({ projectId, canManage, canApprove }: { projectId: string; canManage: boolean; canApprove: boolean }) => {
  const [study, setStudy] = useState<CaseStudy | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const [draft, setDraft] = useState({ internalRetrospective: '', externalCaseStudy: '', demoPackage: '' });
  useEffect(() => { caseStudyApi.forProject(projectId).then((value) => { setStudy(value); if (value) setDraft({ internalRetrospective: value.internalRetrospective, externalCaseStudy: value.externalCaseStudy, demoPackage: value.demoPackage }); }).catch((caught) => setError(getErrorMessage(caught, 'Could not load closure package.'))).finally(() => setLoading(false)); }, [projectId]);
  const run = async () => { setSaving(true); setError(''); try { const result = await caseStudyApi.run(projectId); setStudy(result.caseStudy); setDraft({ internalRetrospective: result.caseStudy.internalRetrospective, externalCaseStudy: result.caseStudy.externalCaseStudy, demoPackage: result.caseStudy.demoPackage }); } catch (caught) { setError(getErrorMessage(caught, 'Could not draft case study.')); } finally { setSaving(false); } };
  const save = async (submitReview = false) => { if (!study) return; setSaving(true); try { setStudy(await caseStudyApi.update(study._id, { ...draft, submitReview })); } catch (caught) { setError(getErrorMessage(caught, 'Could not save closure package.')); } finally { setSaving(false); } };
  const approve = async () => { if (!study) return; setSaving(true); try { setStudy(await caseStudyApi.approve(study._id)); } catch (caught) { setError(getErrorMessage(caught, 'Could not approve external publication.')); } finally { setSaving(false); } };
  if (loading) return <div className="case-study-panel skeleton" style={{ minHeight: 180 }}/>;
  if (!study) return <section className="case-study-panel"><div className="case-study-empty"><Bot size={24}/><h2>Prepare the closure package</h2><p>Generate a retrospective, external case-study draft, and demo scripts from recorded project sources only.</p>{canManage && <button className="btn btn-primary" disabled={saving} onClick={run}>{saving ? 'Preparing…' : 'Run Case Study Agent'}</button>}</div></section>;
  const readOnly = study.status === 'APPROVED' || !canManage;
  return <section className="case-study-panel"><header><div><span><FileVideo size={15}/> Closure package</span><h2>Case study & demo scripts</h2></div><span className={`badge ${study.status === 'APPROVED' ? 'badge-success' : 'badge-warning'}`}>{study.status.replace('_', ' ')}</span></header>{error && <div className="form-error">{error}</div>}
    {study.confidentialityFlags.length > 0 && <div className="case-study-flags"><AlertTriangle size={16}/><div><strong>Publication checks</strong>{study.confidentialityFlags.map((flag) => <p key={flag.type}>{flag.message}</p>)}</div></div>}
    <div className="case-study-sources"><strong>Verified sources</strong>{study.metricSources.map((metric) => <span key={metric.metric}>{metric.metric}: <b>{metric.value}</b> · {metric.sourceType}</span>)}</div>
    <div className="case-study-editors"><label><span>Internal retrospective</span><textarea rows={14} disabled={readOnly} value={draft.internalRetrospective} onChange={(event) => setDraft((current) => ({ ...current, internalRetrospective: event.target.value }))}/></label><label><span>External case study</span><textarea rows={14} disabled={readOnly} value={draft.externalCaseStudy} onChange={(event) => setDraft((current) => ({ ...current, externalCaseStudy: event.target.value }))}/></label><label><span>Demo package</span><textarea rows={14} disabled={readOnly} value={draft.demoPackage} onChange={(event) => setDraft((current) => ({ ...current, demoPackage: event.target.value }))}/></label></div>
    {!readOnly && <footer><button className="btn btn-secondary" disabled={saving} onClick={() => save(false)}><Save size={14}/>Save draft</button>{study.status === 'DRAFT' && <button className="btn btn-secondary" disabled={saving} onClick={() => save(true)}>Submit for CEO review</button>}{canApprove && <button className="btn btn-primary" disabled={saving} onClick={approve}><ShieldCheck size={14}/>Approve external publication</button>}</footer>}{study.status === 'APPROVED' && <div className="case-study-approved"><CheckCircle2 size={15}/> CEO-approved external draft. Content remains read-only.</div>}
  </section>;
};
export default CaseStudyPanel;
